version: '3.7'
services:

  # This is the local MQTT server that is bridged to the central MQTT server
  mqtt:
    image: amrc-factoryplus.***REMOVED***:5000/factory-plus-mqtt-gateway:3.0.0
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    volumes:
      - mosquitto_persistence:/var/lib/mosquitto/
      - mosquitto_conf:/etc/mosquitto
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.fplus-role==cell-gateway
          - node.labels.gw-type!=soft
    networks:
      - factory-plus

  # This is an instance of Node-RED to enable edge logic to be performed 
  node-red:
    image: amrc-factoryplus.***REMOVED***:5000/node-red:1.2.5
    ports:
      - target: 1880
        published: 1880
        protocol: tcp
        mode: host
    environment:
      - TZ=Europe/London
    volumes:
      - node-red_persistence:/data
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.fplus-role==cell-gateway
    networks:
      - factory-plus

  # This is an instance of the Translator app responsible for converting between different protocols and Sparkplug
  translator:
    image: amrc-factoryplus.***REMOVED***:5000/factoryplus-sparkplug-translation-service:2.2.0
    environment:
      - FIELDBUS=false
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - translator_conf:/home/node/app/config
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.fplus-role==cell-gateway
    networks:
      - factory-plus

  
# This is an instance of Ignition Edge to enable the robust connection of supported devices
  ignition_edge:
    image: amrc-factoryplus.***REMOVED***:5000/ignition:8.1.0
    networks:
      - factory-plus
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.fplus-role==cell-gateway
    secrets:
      - admin_password
    volumes:
      - ignition_edge_persistence:/var/lib/ignition/data
    environment:
      GATEWAY_ADMIN_PASSWORD_FILE: /run/secrets/admin_password
      IGNITION_EDITION: 'edge'

  # This is the bacula director that is in charge of scheduling the backups from this node
  baculadirector:
    image: amrc-factoryplus.***REMOVED***:5000/bacula-director:9.6.5
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.fplus-role==cell-gateway
    configs:
      - source: bconsole_config
        target: /opt/bacula/etc/bconsole.conf
    volumes:
      - bacula_director_conf:/opt/bacula/etc
    networks:
      - factory-plus
     
  # This is the bacula client that performs bacups of the local docker volumes 
  baculaclient:
    image: amrc-factoryplus.***REMOVED***:5000/bacula-client:9.6.5
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.fplus-role==cell-gateway
    configs:
      - source: fd_config
        target: /opt/bacula/etc/bacula-fd.conf
      - source: bacula_master_cert
        target: /opt/bacula/etc/bacula-master.cert

    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      - /var/bacula-restore:/tmp/bacula-restores
      - bacula_client_conf:/opt/bacula/etc
    networks:
      - factory-plus
secrets:
  admin_password:
    file: ./ignition_edge/ADMIN_PASSWORD

volumes:
  mosquitto_persistence:
  mosquitto_conf:
  translator_conf:
  bacula_client_conf:
  bacula_director_conf:
  node-red_persistence:
  ignition_edge_persistence:

configs:
  fd_config:
    file: ./bacula/bacula-fd.conf
  bconsole_config:
    file: ./bacula/bconsole.conf
  bacula_master_cert:
    file: ./bacula/master.cert
 

networks:
  factory-plus:
    external: true
    name: factory-plus
